name: WebApp
version: 1.0.0
summary: Azure Web App Environment
description: Deploys a web app in Azure without a datastore
runner: "testrvateacr.azurecr.io/hello-world:v1"
templatePath: main.tf
parameters:
  webAppName:
    type: string
    default: "myWebApp"
  location:
    type: string
    default: "East US"
  sku:
    type: string
    default: "F1"

